steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/nanobanna-pro:latest"
      - "--build-arg"
      - "VITE_SUPABASE_URL=${_VITE_SUPABASE_URL}"
      - "--build-arg"
      - "VITE_SUPABASE_ANON_KEY=${_VITE_SUPABASE_ANON_KEY}"
      # Sensitive keys removed for BYOK security
      - "."

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/nanobanna-pro:latest"

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "nanobanna-pro"
      - "--image"
      - "gcr.io/$PROJECT_ID/nanobanna-pro:latest"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "10"

images:
  # - 'gcr.io/$PROJECT_ID/nanobanna-pro:$COMMIT_SHA'
  - "gcr.io/$PROJECT_ID/nanobanna-pro:latest"

substitutions:
  _VITE_SUPABASE_URL: ""
  _VITE_SUPABASE_ANON_KEY: ""
  # _VITE_AI_KEYS removed

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
