
import fs from 'fs';
import path from 'path';

// Define the output path
const OUTPUT_FILE = path.join(process.cwd(), 'src', 'constants', 'generated_logo_templates.ts');
const ASSETS_DIR = path.join(process.cwd(), 'public', 'assets', 'templates');

// Helper to clean filenames
function cleanName(name: string) {
    return name.replace(/\.[^/.]+$/, "").replace(/[-_]/g, " ");
}

function generateRegistry() {
    if (!fs.existsSync(ASSETS_DIR)) {
        console.error(`Directory not found: ${ASSETS_DIR}`);
        return;
    }

    const files = fs.readdirSync(ASSETS_DIR).filter(file => {
        return /\.(png|jpg|jpeg|mp4|svg)$/i.test(file);
    });

    const templates = files.map(file => {
        const id = file.replace(/\.[^/.]+$/, ""); // remove extension
        const title = cleanName(file);
        const platform = 'linkedin'; // Default
        const type = 'banner'; // Default

        return {
            id: `logo-${id}`.replace(/\s+/g, '-').toLowerCase(),
            title: `Logo: ${title}`,
            industry: 'Branding',
            description: 'Imported Verridian/Logo Asset',
            backgroundUrl: `/assets/templates/${file}`,
            thumbnailUrl: `/assets/templates/${file}`, // Note: Videos might need a poster, but using file URL for now
            prompt: 'Imported asset',
            platform,
            type,
            elements: []
        };
    });

    const content = `// Auto-generated by scripts/generate_logo_registry.ts
import { BannerTemplate } from '../types'; // Assuming types file exists or we need to import from templates.ts? 
// Actually BannerTemplate is exported from templates.ts usually, let's check imports in templates.ts
// It imports BannerElement from '../types'. BannerTemplate is defined in templates.ts inline usually.
// Let's create a shared types file if needed, or just cast as any for the import moment.
// For now, I will NOT import BannerTemplate to avoid circular deps if I modify templates.ts.
// I will just export the array as 'any' or matching the shape.

export const GENERATED_LOGO_TEMPLATES = ${JSON.stringify(templates, null, 2)} as any[];
`;

    fs.writeFileSync(OUTPUT_FILE, content);
    console.log(`Generated ${templates.length} templates in ${OUTPUT_FILE}`);
}

generateRegistry();
